[project]
name = "aoc"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pytest>8"]

[tool.setuptools.packages.find]
include = ["common", "aoc2024", "aoc2025"]
where = ["."]
exclude = []

[tool.pytest.ini_options]
python_files = ["*.py"]
